[font]
size = 10

[font.bold]
family = "Fira Code Medium"
style = "Bold"

[font.bold_italic]
family = "Fira Code Medium"
style = "Bold Italic"

[font.italic]
family = "Fira Code Medium"
style = "Italic"

[font.normal]
family = "Fira Code Medium"
style = "Regular"

